// Code generated by "stringer -type=RunnerType"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Linux-1]
	_ = x[Windows-2]
	_ = x[Mac-3]
	_ = x[SelfHosted-4]
}

const _RunnerType_name = "LinuxWindowsMacSelfHosted"

var _RunnerType_index = [...]uint8{0, 5, 12, 15, 25}

func (i RunnerType) String() string {
	i -= 1
	if i < 0 || i >= RunnerType(len(_RunnerType_index)-1) {
		return "RunnerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RunnerType_name[_RunnerType_index[i]:_RunnerType_index[i+1]]
}
