name: Release
on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - .goreleaser.yaml
      - action.yml
      - Dockerfile
      - go.mod
      - Makefile
      - CHANGELOG.md
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tagpr-tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - id: tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  up-artifact-to-release:
    needs: release
    if: needs.release.outputs.tagpr-tag != ''
    uses: ./.github/workflows/goreleaser.yml
    secrets: inherit
  update-major-version:
    needs: up-artifact-to-release
    uses: ./.github/workflows/update_major_version.yml
    secrets: inherit
